package com.se.state;

public enum State {
	IDLE,
	GENERATING_KEYS,	SENDING_KEYS,	KEYS_RECEIVED,
	
	MEDICAL_CHECKUP,	UNDERGOING_TESTS,	GENERATING_REPORTS,		UPLOADING_RECORDS,
	
	APPLYING_FOR_POLICY,	ACCESSING_RECORDS_AND_GIVING_QUOTES,	CHOOSE_TO_ACCEPT,	REJECT,		PAYING_PREMIUM,		CLAIM_PROCESSED	
}
